@startuml


package "Model" {

class RabbitMQ{
-Producer
-Consumer
}
class USER {
  +telegram_id
}

class AUTHORIZED_USER {
  +telegram_id
  +bookTable()
  +getRestaurantInfo()
  +getMenu()
  +giveFeedback()
}
  class Response{
  -telegram_id
  -type:    String
  -status:  Bool
  -text :   String
  -image:   link_to_image


  }

  class Request {
    +telegram_id
    +request_type
  }

  class BookingRequest {
    +telegram_id
    +request_type
    +tableNumber
    +numberOfGuests
  }

  class RestaurantInfoRequest {
    +telegram_id
    +request_type
  }

  class MenuRequest {
    +telegram_id
    +request_type
  }

  class FeedbackRequest {
    +telegram_id
    +request_type
    +feedbackText
  }

  Request <|-- BookingRequest
  Request <|-- RestaurantInfoRequest
  Request <|-- MenuRequest
  Request <|-- FeedbackRequest
}

package "View" {
  class TelegramView {
    +displayMenu()
    +displayRestaurantInfo()
    +displayBookingForm()
    +displayFeedbackForm()
  }
}

package "Controller" {

  class RMQController{
  +send_request_to_rmq()
  }
  class ResponseController{
  -response:Response
'  +receive_response_from_rmq()
  +send_response_to_telegram_controller(response)
  }
  class RequestController{
  -request:Request
  +send_request_to_rmq_ctrl()
  }
  class TelegramController {
    -request: Request
    -view: TelegramView

    +create_request(view)
    +receive_request(request)
    +send_to_telegram(view)
  }
}


ResponseController -> TelegramController
ResponseController -- Response
RequestController -- Request
USER <|-- AUTHORIZED_USER
TelegramView *-- TelegramController
TelegramController --> Request
RMQController --> RabbitMQ

@enduml