@startuml

left to right direction
skinparam actor {
  BorderColor DarkSlateGray
  BackgroundColor LightBlue
}

actor User as "User"
actor AuthUser as "Auth User"
actor RinaBrain as "Rina Brain"

rectangle "Restaurant System" {
  User --> (Authorize)
  User --> (Get Restaurant Info)
  User --> (Get Menu View)

  AuthUser --> (Call for Waiter)
  AuthUser --> (Get Order)
  AuthUser --> (Book Table)
  AuthUser --> (Input Personal Client Data)
  AuthUser --> (Give Feedback)
  AuthUser --> (Receive Advertisement)

  (Authorize)                 <-- RinaBrain
  (Get Restaurant Info)       <--  RinaBrain
 (Get Menu View)              <--  RinaBrain
 (Call for Waiter)            <--  RinaBrain
 (Get Order)                  <--  RinaBrain
 (Book Table)                 <--  RinaBrain
 (Input Personal Client Data) <--  RinaBrain
 (Give Feedback)              <--  RinaBrain
 (Receive Advertisement)      <--  RinaBrain
}
@enduml
